### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by TechyGuy17** [Kononenko-K/Allwinner_H616_Devboard#1]
Hello! 

I love this project, been looking for a good and simple h616 circuit and this is great!!

Do you have any recommendation regarding sourcing? For example the AXP305 seems to have dissapered from lcsc, do you solder it yourself?

And is there a reason you use a 25mhz reference clock instead of the recommended 24 in the datasheet of the h616?

Thanks!

**Comment by Kononenko-K** [comment]
Hello! Thanks for the Feedback!

I used AXP305 to make this board fully compatible with Orange Pi Zero 2 Device Tree and defconfig in mainline U-Boot and Linux kernel. Using a different PMIC would mean changing the Device Tree, and maybe some extra manipulation with the power drivers. You can order this IC on Aliexpress, I personally bought it there.

Speaking of crystal resonators, you're right. There was a mistake in the schematic. Already fixed it. It should be 24 MHz.
